### ISSUE TITLE
how to get the single chain pdb from pdb file

### ISSUE THREAD

**Issue by fishguysword** [psipred/protein-vae#2]
I want to caculate the tmscore between the stardard pdb and the database pdb .example  2YSS_A and 1OAQ_L the pdb website offer the whole pdb contain two chain. how to get the single chain pdb information and use the TM-align caculate the score?  can you give me a hand

**Comment by jgreener64** [comment]
If you want to extract a chain from a PDB file, for a single case you can open the PDB file and copy out the ATOM/HETATM lines for the chain in question to a new file. The chain ID is the 22nd character of each ATOM/HETATM line.

To do this programmatically the easiest way is probably to use [pdb-tools](https://github.com/haddocking/pdb-tools):

```
pip install pdb-tools
pdb_selchain -A 2YSS.pdb > 2YSS_A.pdb
```

Then you can run TM-align with that file. I don't fully understand the first part of your question though. Hope this helps!

**Comment by fishguysword** [comment]
very helpful! thanks for your kindness .
